INFO	2021-11-10 16:38:10,803	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:38:12,784	[basepage.py:90]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-11-10 16:38:13,538	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:38:14,353	[basepage.py:90]	点击元素：('css', 'body>div>div>div>div>p>a')
WARNING	2021-11-10 16:38:23,526	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD55CFC400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be/timeouts
WARNING	2021-11-10 16:38:25,262	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002003451C3D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341/timeouts
WARNING	2021-11-10 16:38:25,547	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD55DA1C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be/timeouts
WARNING	2021-11-10 16:38:27,288	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200345C1FA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341/timeouts
WARNING	2021-11-10 16:38:27,598	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD55DA1D60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be/timeouts
WARNING	2021-11-10 16:38:29,325	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200345C1B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341/timeouts
WARNING	2021-11-10 16:38:31,819	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD55DA1640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be
WARNING	2021-11-10 16:38:33,539	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200345C1670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341
WARNING	2021-11-10 16:38:33,841	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD560AAA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be
WARNING	2021-11-10 16:38:35,573	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200348CBEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341
WARNING	2021-11-10 16:38:35,880	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD560AAE80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e2162b3c3b4cce990d6b6a7dcf7708be
WARNING	2021-11-10 16:38:37,606	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200348CBEB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b3574f1bf8dcac2fb2e1fad2b4b17341
INFO	2021-11-10 16:42:58,018	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:42:58,165	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:42:58,990	[basepage.py:90]	点击元素：('css', 'body>div>div>div>div>p>a')
INFO	2021-11-10 16:43:04,154	[basepage.py:90]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
WARNING	2021-11-10 16:43:11,808	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5D9E4A460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1/timeouts
WARNING	2021-11-10 16:43:13,844	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5D9EF1EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1/timeouts
WARNING	2021-11-10 16:43:15,099	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF948D400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d/timeouts
WARNING	2021-11-10 16:43:15,889	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5D9EF1370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1/timeouts
WARNING	2021-11-10 16:43:17,138	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF9531C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d/timeouts
WARNING	2021-11-10 16:43:19,175	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF9531D60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d/timeouts
WARNING	2021-11-10 16:43:20,073	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5D9EF1730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1
WARNING	2021-11-10 16:43:22,117	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5DA19FF70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1
WARNING	2021-11-10 16:43:23,375	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF9531640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d
WARNING	2021-11-10 16:43:24,161	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B5DA19FA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0f0ab1e5335aa724391a4b16bc05c5e1
WARNING	2021-11-10 16:43:25,410	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF9839A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d
WARNING	2021-11-10 16:43:27,454	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAF9839E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b7e99e5cc3648ce9dea62ed01a4b436d
INFO	2021-11-10 16:51:57,934	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:51:57,978	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 16:51:58,995	[basepage.py:90]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-11-10 16:51:59,753	[basepage.py:90]	点击元素：('css', 'body>div>div>div>div>p>a')
WARNING	2021-11-10 16:52:10,332	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C917B460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81/timeouts
WARNING	2021-11-10 16:52:10,379	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4F7CD430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34/timeouts
WARNING	2021-11-10 16:52:12,367	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C9221970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81/timeouts
WARNING	2021-11-10 16:52:12,412	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4F875E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34/timeouts
WARNING	2021-11-10 16:52:14,388	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C9221580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81/timeouts
WARNING	2021-11-10 16:52:14,436	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4F875CD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34/timeouts
WARNING	2021-11-10 16:52:18,577	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C9221730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81
WARNING	2021-11-10 16:52:18,626	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4F8758B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34
WARNING	2021-11-10 16:52:20,624	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C952EC10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81
WARNING	2021-11-10 16:52:20,670	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4FB04F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34
WARNING	2021-11-10 16:52:22,662	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182C952EA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0a747d8a7624557ea5bfbfab85f2cb81
WARNING	2021-11-10 16:52:22,710	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C4FB04A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4e2295ed1822c2b3b292dcb262730e34
INFO	2021-11-10 17:39:17,540	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 17:39:17,618	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-11-10 17:39:18,497	[basepage.py:90]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-11-10 17:39:19,473	[basepage.py:90]	点击元素：('css', 'body>div>div>div>div>p>a')
