WARNING	2021-10-18 10:13:34,803	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1BD1B160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:13:35,004	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F98DB130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:13:36,837	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1BE29460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:13:37,041	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F99E93A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:13:38,885	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1BE297F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:13:39,087	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F99E9730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:13:43,088	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C1C8CD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:13:43,272	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9D88DC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
WARNING	2021-10-18 10:13:45,119	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C0923D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:13:45,306	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9BBD340>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
WARNING	2021-10-18 10:13:47,160	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C092250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:13:47,335	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9BBD580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
WARNING	2021-10-18 10:14:11,234	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C00D910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:14:11,462	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9C1FB20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:14:13,275	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C00D940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:14:13,496	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9C1F7F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:14:15,327	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C00DA00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5/timeouts
WARNING	2021-10-18 10:14:15,543	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9C1F9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785/timeouts
WARNING	2021-10-18 10:14:19,542	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1BCD8E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:14:19,758	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9DA3BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
WARNING	2021-10-18 10:14:21,589	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C025160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:14:21,808	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9EC6580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
WARNING	2021-10-18 10:14:23,609	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012B1C30AE50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4d7dc4466be4a4eb5df4585f1362e1c5
WARNING	2021-10-18 10:14:23,842	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000147F9EC6280>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9e699f8c40c90a8cdaf4b6c6081c3785
INFO	2021-10-18 10:16:46,557	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:16:46,731	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:16:48,612	[basepage.py:88]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-10-18 10:16:48,876	[basepage.py:88]	点击元素：('css', 'body>div>div>div>div>p>a')
INFO	2021-10-18 10:17:19,525	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:17:19,734	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:17:22,404	[basepage.py:88]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-10-18 10:17:22,676	[basepage.py:88]	点击元素：('css', 'body>div>div>div>div>p>a')
INFO	2021-10-18 10:18:53,250	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:18:53,383	[basepage.py:32]	打开网页https://www.imymac.com/free-imymac-pdf-compressor/
INFO	2021-10-18 10:18:56,520	[basepage.py:88]	点击元素：('css', 'body>div.pdfFooter>div>div.text-center>a')
INFO	2021-10-18 10:19:01,375	[basepage.py:88]	点击元素：('css', 'body>div>div>div>div>p>a')
