[32mINFO    [0m root:basepage.py:32 打开网页https://www.imymac.com/sitemap/
[32mINFO    [0m root:basepage.py:96 获取到文本：Convert WMA to MP3 Online for Free with High Quality
[32mINFO    [0m root:basepage.py:96 获取到文本：Convert WMA to MP3 Online for Free with High Quality
[32mINFO    [0m root:basepage.py:96 获取到文本：Convert WMA to MP3 Online for Free with High Quality
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD0D670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD61E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD61730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B118520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B0E0B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B0E0A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2